global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'webapi'
    scheme: https
    static_configs:
      - targets: ['localhost:7001']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
