global:
  scrape_interval: 15s
  scrape_timeout: 10s
  # evaluation_interval: 15s

alerting:
  alertmanagers:
  - scheme: http
    timeout: 10s
    api_version: v1
    static_configs:
    - targets: []

scrape_configs:
  - job_name: webapi
    honor_timestamps: true
    scrape_interval: 15s  
    scrape_timeout: 10s  
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: 
        - host.docker.internal:7000
  - job_name: 'vmagent'
    static_configs:
      - targets: ['host.docker.internal:8429']
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['host.docker.internal:8428']
  - job_name: node-exporter
    static_configs:
      - targets: ['host.docker.internal:9100']